name: Harbour for Win64 using msvc

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4

      - name: Checkout FiveTechSoft/harbour repo
        uses: actions/checkout@v4
        with:
          repository: FiveTechSoft/harbour
          path: harbour

      - name: Installing dependencies
        shell: cmd
        run: |
          vcpkg.exe install curl:x64-windows
          vcpkg.exe install openssl:x64-windows
          vcpkg integrate install

      - name: Fixing Harbour hbssl.hbp
        run: |
          (Get-Content -path harbour\contrib\hbssl\hbssl.hbp) -replace 'libeay32','libcrypto-1_1-x64' | Set-Content -path harbour\contrib\hbssl\hbssl.hbp
          (Get-Content -path harbour\contrib\hbssl\hbssl.hbp) -replace 'ssleay32','libssl-1_1-x64' | Set-Content -path harbour\contrib\hbssl\hbssl.hbp
          (Get-Content -path harbour\contrib\hbssl\hbssl.hbc) -replace 'libeay32','libcrypto' | Set-Content -path harbour\contrib\hbssl\hbssl.hbc
          (Get-Content -path harbour\contrib\hbssl\hbssl.hbc) -replace 'ssleay32','libssl' | Set-Content -path harbour\contrib\hbssl\hbssl.hbc

      - name: Setup MSVC environment (x64)
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Compile and install Harbour
        shell: cmd
        run: |
          cd harbour
          set HB_BUILD_MODE=c
          set HB_USER_PRGFLAGS=-l-
          set HB_BUILD_CONTRIBS=
          set HB_WITH_OPENSSL=c:\vcpkg\packages\openssl-windows_x64-windows\include\
          set HB_WITH_CURL=c:\vcpkg\packages\curl_x64-windows\include
          set HB_OPENSSL_STATIC=yes
          set HB_STATIC_OPENSSL=yes
          set HB_STATIC_CURL=yes
          set HB_BUILD_DYN=no
          set HB_BUILD_CONTRIB_DYN=no
          set HB_COMPILER=msvc64
          set HB_INSTALL_PREFIX=%GITHUB_WORKSPACE%\output
          win-make.exe || exit /b 1
          win-make.exe install || exit /b 1

      - name: Get current time
        id: current-time
        shell: pwsh
        run: |
          $time = Get-Date -Format "yyyy_MM_dd"
          "formattedTime=$time" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: Upload mod_harbour to artifact
        env:
           TIME: "${{ steps.current-time.outputs.formattedTime }}"
        uses: actions/upload-artifact@v4
        with:
          name: harbour_win64_msvc_${{ env.TIME }}
          path: output
