name: Harbour for Windows 64 using BCC

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2022


    steps:
    - name: Checkout FiveTechSoft/harbour repo
      uses: actions/checkout@v4
      with:
       repository: FiveTechSoft/harbour
       path: harbour

    - name: Install dependencies
      run: |
         (new-object System.Net.WebClient).DownloadFile('https://bitbucket.org/lorenzodla/mod_harbour_actions_resources/downloads/OpenSSL-Win32.zip', 'C:\temp\OpenSSL-Win32.zip')
         Expand-Archive -LiteralPath C:\temp\OpenSSL-Win32.zip -DestinationPath C:\OpenSSL -Force
         (new-object System.Net.WebClient).DownloadFile('https://bitbucket.org/lorenzodla/mod_harbour_actions_resources/downloads/curl-7.54.0-win32-mingw.zip', 'C:\temp\curl-7.54.0-win32-mingw.zip')
         Expand-Archive -LiteralPath C:\temp\curl-7.54.0-win32-mingw.zip -DestinationPath C:\curl -Force
         (new-object System.Net.WebClient).DownloadFile('https://github.com/FiveTechSoft/Harbour_builder/raw/fix/android-ci-header-pollution/.github/temp/bcc7764_bin_lib.zip', 'C:\temp\bcc7764_bin_lib.zip')
         Expand-Archive -LiteralPath C:\temp\bcc7764_bin_lib.zip -DestinationPath C:\bcc77 -Force
         (new-object System.Net.WebClient).DownloadFile('https://github.com/FiveTechSoft/Harbour_builder/raw/fix/android-ci-header-pollution/.github/temp/bcc7764_include.zip', 'C:\temp\bcc7764_include.zip')
         Expand-Archive -LiteralPath C:\temp\bcc7764_include.zip -DestinationPath C:\bcc77 -Force

    - name: Patch sources for BCC64
      shell: pwsh
      run: |
        (new-object System.Net.WebClient).DownloadFile('https://github.com/FiveTechSoft/Harbour_builder/raw/fix/android-ci-header-pollution/.github/temp/patch_hbmk2_bcc64.py', 'C:\temp\patch_hbmk2_bcc64.py')
        python C:\temp\patch_hbmk2_bcc64.py harbour\utils\hbmk2\hbmk2.prg

    - name: Compile and install Harbour
      shell: cmd
      run: |
        cd harbour
        set path=c:\bcc77\bin
        set INCLUDE=c:\bcc77\Include;C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\um;C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\shared;C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\ucrt
        set LIB=c:\bcc77\lib;C:\Program Files (x86)\Windows Kits\10\Lib\10.0.26100.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\10\Lib\10.0.26100.0\um\x64
        set HB_BUILD_MODE=c
        set HB_USER_CFLAGS=
        set HB_USER_LDFLAGS=-L"c:\bcc77\lib" -L"c:\bcc77\lib\psdk"
        set HB_USER_PRGFLAGS=-l-
        set HB_BUILD_CONTRIBS=
        set HB_WITH_OPENSSL=C:\OpenSSL\include
        set HB_WITH_CURL=C:\curl\include
        set HB_STATIC_OPENSSL=yes
        set HB_STATIC_CURL=yes
        set HB_COMPILER=bcc64
        SET HB_BUILD_CONTRIB_DYN=no
        SET HB_BUILD_DYN=no
        set HB_INSTALL_PREFIX=%GITHUB_WORKSPACE%\output
        win-make.exe src || exit /b 1
        win-make.exe -C src install || exit /b 1

    - name: Get current time
      id: current-time
      shell: pwsh
      run: |
        $time = Get-Date -Format "yyyyMMdd"
        "formattedTime=$time" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

    - name: Upload Harbour to artifact
      env:
       TIME: "${{ steps.current-time.outputs.formattedTime }}"
      uses: actions/upload-artifact@v4
      with:
       name: harbour_win64_bcc_${{ env.TIME }}
       path: output
