name: Harbour for Windows 32 using BCC

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2022


    steps:
    - name: Checkout FiveTechSoft/harbour repo
      uses: actions/checkout@v4
      with:
       repository: FiveTechSoft/harbour
       path: harbour

    - name: Install dependencies
      run: |
         (new-object System.Net.WebClient).DownloadFile('https://bitbucket.org/lorenzodla/mod_harbour_actions_resources/downloads/OpenSSL-Win32.zip', 'C:\temp\OpenSSL-Win32.zip')
         Expand-Archive -LiteralPath C:\temp\OpenSSL-Win32.zip -DestinationPath C:\OpenSSL -Force
         (new-object System.Net.WebClient).DownloadFile('https://bitbucket.org/lorenzodla/mod_harbour_actions_resources/downloads/curl-7.54.0-win32-mingw.zip', 'C:\temp\curl-7.54.0-win32-mingw.zip')
         Expand-Archive -LiteralPath C:\temp\curl-7.54.0-win32-mingw.zip -DestinationPath C:\curl -Force
         (new-object System.Net.WebClient).DownloadFile('https://github.com/FiveTechSoft/Harbour_builder/raw/master/.github/temp/win32/bcc7/libcurl.lib', 'C:\temp\libcurl.zip')
         (new-object System.Net.WebClient).DownloadFile('https://github.com/FiveTechSoft/Harbour_builder/raw/master/.github/temp/bcc77.zip', 'C:\temp\bcc77.zip')
         Expand-Archive -LiteralPath C:\temp\bcc77.zip -DestinationPath C:\bcc77 -Force
         (new-object System.Net.WebClient).DownloadFile('https://bitbucket.org/lorenzodla/mod_harbour_actions_resources/downloads/acesdk.zip', 'C:\temp\acesdk.zip')
         Expand-Archive -LiteralPath C:\temp\acesdk.zip -DestinationPath C:\acesdk -Force

    - name: Compile and install Harbour
      shell: cmd
      run: |
        cd harbour
        set path=c:\bcc77\bin
        set LIB=c:\bcc77\lib
        set HB_BUILD_MODE=c
        set HB_USER_CFLAGS=-w-sig -w-8071 -w-8084
        set HB_USER_PRGFLAGS=-l-
        set HB_BUILD_CONTRIBS=
        set HB_WITH_OPENSSL=C:\OpenSSL\include
        set HB_WITH_CURL=C:\curl\include
        set HB_WITH_ADS=C:\acesdk
        set HB_STATIC_OPENSSL=yes
        set HB_STATIC_CURL=yes
        set HB_COMPILER=bcc
        SET HB_BUILD_CONTRIB_DYN=no
        SET HB_BUILD_DYN=no
        set HB_USER_RESFLAGS=-Ic:\\bcc77\\include\\windows\\sdk\\ -w
        set HB_INSTALL_PREFIX=%GITHUB_WORKSPACE%\output
        win-make.exe || exit /b 1
        win-make.exe install || exit /b 1
        if exist "%GITHUB_WORKSPACE%\temp\libcurl.lib" copy "%GITHUB_WORKSPACE%\temp\libcurl.lib" "%HB_INSTALL_PREFIX%\lib\win\bcc\"

    - name: Get current time
      id: current-time
      shell: pwsh
      run: |
        $time = Get-Date -Format "yyyyMMdd"
        "formattedTime=$time" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

    - name: Upload Harbour to artifact
      env:
       TIME: "${{ steps.current-time.outputs.formattedTime }}"
      uses: actions/upload-artifact@v4
      with:
       name: harbour_win32_bcc_${{ env.TIME }}
       path: output
