name: Harbour for Ubuntu 64-bits

on:
  push:
  watch:
   types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    
    if: github.actor == github.event.repository.owner.login
    
    steps:
    - name: Checkout mod_harbour repo
      uses: actions/checkout@v2
    
    - name: Checkout harbour/core repo
      uses: actions/checkout@v2
      with:
       repository: harbour/core
       path: harbour

    - name: Install dependencies
      run: |
         sudo apt install libcurl4-openssl-dev libssl-dev gcc
         sudo cp -r /usr/include/x86_64-linux-gnu/curl /usr/include
         
    - name: Compile harbour
      run: |
        cd harbour
        export HB_USER_CFLAGS="-fPIC"
        export HB_BUILD_CONTRIBS
        export HB_WITH_PCRE=local
        make
        
    - name: Create output folders
      run: |
        mkdir output
        mkdir output/bin
        cp harbour/bin/linux/gcc/* output/bin
        mkdir output/lib
        cp harbour/lib/linux/gcc/*.a output/lib
        mkdir output/include 
        cp harbour/include/* output/include        
        
    - name: Get current time
      uses: srfrnk/current-time@master
      id: current-time
      with:
        format: YYYY_MM_DD
 
    - name: Upload Harbour to artifact
      env:
         TIME: "${{ steps.current-time.outputs.formattedTime }}"
      uses: actions/upload-artifact@v2
      with:
       name: harbour_ubuntu_64_${{ env.TIME }}
       path: output     
