name: Harbour for Ubuntu 64-bits

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
    - name: Checkout mod_harbour repo
      uses: actions/checkout@v4

    - name: Checkout FiveTechSoft/harbour repo
      uses: actions/checkout@v4
      with:
       repository: FiveTechSoft/harbour
       path: harbour

    - name: Install dependencies
      run: |
         sudo apt update
         sudo apt install -y libcurl4-openssl-dev libssl-dev gcc
         sudo cp -r /usr/include/x86_64-linux-gnu/curl /usr/include

    - name: Compile and install harbour
      run: |
        cd harbour
        export HB_USER_CFLAGS="-fPIC"
        export HB_BUILD_CONTRIBS
        export HB_WITH_PCRE=local
        export HB_INSTALL_PREFIX="$GITHUB_WORKSPACE/output"
        make
        make install

    - name: Get current time
      id: current-time
      run: echo "formattedTime=$(date +%Y_%m_%d)" >> "$GITHUB_OUTPUT"

    - name: Upload Harbour to artifact
      env:
         TIME: "${{ steps.current-time.outputs.formattedTime }}"
      uses: actions/upload-artifact@v4
      with:
       name: harbour_ubuntu_64_${{ env.TIME }}
       path: output
