name: Harbour for Apple Darwin

on:
  push:
  watch:
   types: [started]

jobs:
  build:
    runs-on: macos-latest
    
    if: github.actor == github.event.repository.owner.login
    
    steps:
    - name: Checkout harbour/core repo
      uses: actions/checkout@v2
      with:
       repository: harbour/core
       path: harbour

    - name: Install dependencies
      run: |
         brew install curl
         brew install pcre
         
    - name: Compile Harbour
      run: |
        cd harbour
        export HB_WITH_CURL=/usr/local/Cellar/curl/7.69.1/include/
        export HB_BUILD_CONTRIBS=""
        make
        
    - name: Create output folders
      run: |
        mkdir output
        mkdir output/bin
        cp harbour/bin/darwin/clang/* output/bin
        mkdir output/lib
        cp harbour/lib/darwin/clang/*.a output/lib
        mkdir output/include 
        cp harbour/include output/include
        
    - name: Get current time
      uses: srfrnk/current-time@master
      id: current-time
      with:
        format: YYYY_MM_DD
 
    - name: Upload Harbour to artifact
      env:
         TIME: "${{ steps.current-time.outputs.formattedTime }}"
      uses: actions/upload-artifact@v2
      with:
       name: harbour_darwin_osx_${{ env.TIME }}
       path: output        
      
