name: Harbour for Apple Darwin

on:
  push:
  watch:
   types: [started]

jobs:
  build:
    runs-on: macos-latest
    
    if: github.actor == github.event.repository.owner.login
    
    steps:
    - name: Checkout harbour/core repo
      uses: actions/checkout@v2
      with:
       repository: harbour/core
       path: harbour

    - name: Install dependencies
      run: |
         brew install curl
         brew install pcre
         
    - name: Compile Harbour
      run: |
        cd harbour
        export HB_WITH_CURL=/usr/local/Cellar/curl/7.69.1/include/
        export HB_BUILD_CONTRIBS=""
        make
      
